#pragma once

// VDB Geometry to Grid Plugin
// Initial code generated by Softimage SDK Wizard
// Executed Fri Nov 1 23:31:00 UTC+0200 2013 by OlegCore
// 
// 
// Tip: You need to compile the generated code before you can load the plug-in.
// After you compile the plug-in, you can load it by clicking Update All in the Plugin Manager.
#include <xsi_application.h>
#include <xsi_context.h>
#include <xsi_pluginregistrar.h>
#include <xsi_status.h>

#include <xsi_icenodecontext.h>
#include <xsi_icenodedef.h>
#include <xsi_command.h>
#include <xsi_factory.h>
#include <xsi_longarray.h>
#include <xsi_doublearray.h>
#include <xsi_math.h>
#include <xsi_vector2f.h>
#include <xsi_vector3f.h>
#include <xsi_vector4f.h>
#include <xsi_matrix3f.h>
#include <xsi_matrix4f.h>
#include <xsi_rotationf.h>
#include <xsi_quaternionf.h>
#include <xsi_color4f.h>
#include <xsi_shape.h>
#include <xsi_icegeometry.h>
#include <xsi_iceportstate.h>
#include <xsi_indexset.h>
#include <xsi_dataarray.h>
#include <xsi_dataarray2D.h>


#define VDB_DATA_DESC L"VDBGrid reference"
#define VDB_NODE_COLOR 200,200,200
#define VDB_PUT_CATEGORIES_NAME L"Open VDB"
#define VDB_STREAM_COLOR 190,40,40 
#define VDB_DATA_NAME L"VDBGridRef"

using namespace XSI; 
